<?php

/**
 * Cadde1905 - Demo İçerik ve Referans Veri Sicili
 */

return [
    'App\Models\News' => [
        'parcali-formayi-giymeye-hazir-ilkay-gundogan-geliyor',
        'durdurulamayan-aslan-victor-osimhenden-3-gol-birden',
        'sampiyonlar-ligi-ceyrek-finalinde-rakip-bayern-munih',
        'galatasaray-daikin-cev-kupasi-yari-finalinde-avantaji-kapti',
        'akademi-meyvelerini-veriyor-3-genc-yildiz-a-takima-cikti',
        'parkenin-aslanlari-derbide-geri-dondu',
        'icardinin-galatasaray-aski-bitmiyor-sosyal-medya-sallandi',
        'kombineler-tukendi-mac-gunu-gelirlerinde-tarihi-zirve',
        'tekerlekli-sandalye-basketbolda-final-four-heyecani-basliyor',
        'efsane-uefa-kupasi-formasi-yeniden-satista',
    ],
    'App\Models\Legend' => [
        'ali-sami-yen',
        'metin-oktay',
        'fatih-terim',
        'gheorghe-hagi',
        'bulent-korkmaz',
        'fernando-muslera',
        'claudio-taffarel',
        'cevad-prekazi',
        'jupp-derwall',
        'mauro-icardi',
    ],
    'App\Models\HistoryEvent' => [
        'aglari-yirtan-gol-metin-oktay-1959',
        'prekazinin-fuzeye-donusen-serbest-vurusu-1989',
        'taffarelin-henryye-dur-dedigi-an-17-mayis-2000',
        'popescunun-son-penaltisi-ve-kupa-17-mayis-2000',
        'jardelin-altin-goluyle-super-kupa-25-agustos-2000',
        'kadikoyde-karanlikta-kalkan-kupa-12-mayis-2012',
        'drogbanin-real-madride-attigi-topuk-golu-2013',
        'sneijderin-karda-juventusu-yiktigi-an-11-aralik-2013',
        '4-yildizin-takildigi-an-2015',
        'icardinin-old-traffordu-susturusu-2023',
        'uefa-cup-title-2000',
        'uefa-super-cup-title-2000',
        'iffhs-first-2001',
        'europe-semi-1989',
        'first-fourth-star-2015',
        'wheelchair-basketball-dominance',
        'euroleague-women-2014',
        'four-in-a-row-1996-2000',
        'ucl-quarterfinal-tradition',
        'cup-lord-18',
    ],
    'App\Models\Trophy' => [
        'super-lig',
        'turkiye-kupasi',
        'uefa-kupasi',
        'uefa-super-kupa',
        'euroleague-women',
        'turkiye-basketbol-sampiyonlugu',
        'avrupa-kupasi-finali',
        'tsb-avrupa-kupasi',
    ],
    'App\Models\HistoricalMatch' => [
        'kopenhag-destani-uefa-kupasi-sampiyonlugu',
        'super-kupa-bizim-dunyanin-en-buyugu-cimbom',
        'ali-sami-yende-mucize-uefa-yolu-aciliyor',
        'old-traffordda-tarih-yazildi-cehenneme-hos-geldiniz',
        'karanlikta-parlayan-kupa-kadikoy-sampiyonlugu',
        'drogba-ve-sneijderden-madride-kabus',
        'karlar-icinden-gelen-zafer-sneijderin-imzasi',
        '3-0in-rovansinda-5-0lik-inanilmaz-geri-donus',
        'old-traffordda-30-yil-sonra-yeniden',
        'turkiye-kupasi-finalinde-tarihi-skor',
    ],
    'App\Models\SeasonArchive' => [
        '1905-kurucu-sezon',
        '1986-1987-14-yillik-hasretin-sonu',
        '1992-1993-feldkamp-ile-gelen-cifte-kupa',
        '1996-1997-fatih-terim-donemi-basliyor',
        '1999-2000-altin-yil-the-golden-season',
        '2005-2006-16-dakikalik-mucize',
        '2011-2012-yeniden-dogus-ve-kadikoy-zaferi',
        '2013-2014-avrupada-istikrar-ve-drogba-etkisi',
        '2014-2015-4-yildizin-takildigi-yil',
        '2022-2023-cumhuriyetin-100-yil-sampiyonlugu-sezonu',
    ],
];
